### ISSUE TITLE
Format of timestamp

### ISSUE THREAD

**Issue by cray74** [novalabs/annotations-panel#1]
Hi,

thanks for this nice pluging. I'm having trouble though entering a timestamp (leaving it empty, ie. "now") is working. Which timestamp format should I use?

Thanks for your help!

Kind regards,

Dietmar

**Comment by cray74** [comment]
Never mind, I've figured it out by looking at the code (as I should have in the first place...). Anyways, our company would be interested in have a few additions implemented (paid/donation). In order of our priority:

1. turn timestamp-field into a datetime-picker
2. clicking on any point in a graph on the current screen should fill the timestamp-field
3. delete annotations - probably more a feature request for Grafana?

Would you be interested to implement this for us?

Kind regards,

Dietmar

**Comment by cray74** [comment]
Never mind, just noticed all this is going to be implemented in Grafana 4.4.

Thanks anyways.

**Comment by nleali-novalabs** [comment]
Hi!
Sorry for lateness.
The timestamp format is the same of influxDB: Unix nanoseconds timestamp. E.g.: 1434055562000000000

[Here](https://github.com/grafana/grafana-plugin-repository/pull/112#issuecomment-301893439) more about future Grafana annotations support and difference between this plugin.

Bye

**Comment by cray74** [comment]
Hi,


thanks for your valuable feedback! As we'll have our events in InfluxDB, we'll definitely going to continue using your plugin. On that score - are you planning to implement  some of the features I've mentioned (datetime-picker for example)?


Cheers,


Dietmar


________________________________
