### ISSUE TITLE
Annotation update/delete feature request

### ISSUE THREAD

**Issue by Atrejoe** [novalabs/annotations-panel#6]
It would be nice to be able to update / delete annotations in the UI

**Comment by OverWorldD** [comment]
I second this, how do I delete an annotation?

**Comment by nleali-novalabs** [comment]
Hi!
When you create an annotation, it is saved in your influxDB database as a single data point.

From InfluxDB documentation:

> Deletes are a rare occurrence. When they do occur it is almost always against large ranges of old data that are cold for writes.
> 
> Pro: Restricting access to deletes allows for increased query and write performance.
> Con: Delete functionality is significantly restricted.

and this panel follow this design choice. When you store an annotation, you "register" an event that is surely happen. 
If you want to be able to delete frequently your annotations, I suggest you to use a different datasource, e.g.: sql, or to implement by yourself a slow query like:

`DELETE WHERE time = 1496677645917952139`

or to check new Grafana Annotation Support (build-in): [link](http://docs.grafana.org/reference/annotations/)

At the moment, here, there is no support for this operation.

Greetings
